#:schema node_modules/wrangler/config-schema.json
name = "subconvert"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "85919c524b3d40a3bf163d1b82f13f7d" }
]
